Criação das classes base
LuisRotoly/CRPreparacoesBackEnd pull request #1
Opened 2023-08-31 21:04 UTC by LuisRotoly

Criação das classes cliente, motos, peças, fornecedores e uma junção entre cliente e suas motos

2023-09-05 01:06 UTC, gudominguete requested changes

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/bike/CreateBike.java
> +@Getter
Trocar para `@Data`

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/bike/CreateBike.java
> +public class CreateBike {
É um RequestObjetct? se for aconselho a trocar o nome

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/bike/EditBike.java
> +public class EditBike {
Mesmos comentarios acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/client/CreateClient.java
> +public class CreateClient {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/client/EditClient.java
> +public class EditClient {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/clientBikes/CreateClientBikes.java
> +public class CreateClientBikes {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/clientBikes/EditClientBikes.java
> +public class EditClientBikes {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/part/CreatePart.java
> +public class CreatePart {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/part/EditPart.java
> +public class EditPart {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/supplier/CreateSupplier.java
> +public class CreateSupplier {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/supplier/EditSupplier.java
> +public class EditSupplier {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/BikeController.java
> +    public @ResponseBody void addBike(@RequestBody CreateBike createBike){
Acho q não precisa do `@ResponseBody` por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/BikeController.java
> +    public @ResponseBody void editBike(@RequestBody EditBike editBike){
Acho q não precisa do `@ResponseBody` por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/ClientBikesController.java
> +    public @ResponseBody void addClientBikes(@RequestBody CreateClientBikes createClientBikes){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/ClientBikesController.java
> +    public @ResponseBody void editClientBikes(@RequestBody EditClientBikes editClientBikes){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/ClientController.java
> +    public @ResponseBody void addClient(@RequestBody CreateClient createClient){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/ClientController.java
> +    public @ResponseBody void editClient(@RequestBody EditClient editClient){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/PartController.java
> +    public @ResponseBody void addPart(@RequestBody CreatePart createPart){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/PartController.java
> +    public @ResponseBody void editPart(@RequestBody EditPart editPart){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/SupplierController.java
> +    public @ResponseBody void addSupplier(@RequestBody CreateSupplier createSupplier){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/controllers/SupplierController.java
> +    public @ResponseBody void editSupplier(@RequestBody EditSupplier editSupplier){
Acho q não precisa do @ResponseBody por ser void

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/exception/ApiException.java
> +@Setter
Trocar para `@Data`

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Bike.java
> +@Getter
trocar para `@Data`

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Bike.java
> +public class Bike {
Precisa de um construtor?

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Client.java
> +public class Client {
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/ClientBikes.java
> +@Setter
Mesmo comentário acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/ClientBikes.java
> +@Table(name="client_bikes")
remover o plural da tabela

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Part.java
> +@Getter
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Part.java
> +public class Part {
O que seria essa part?

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Supplier.java
> +@Setter
Mesmos comentários acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/BikeRepository.java
> +    List<Client> listAllBikes();
Não seria List<Bike> ?

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/BikeRepository.java
> +    void editBikeById(Long idBike, String name, String brand, Integer engineCapacity, String year, LocalDateTime updatedAt);
Não precisa criar essa function. Pode usar a save do JPA normal. Qdo ele tem o ID, ele edita, qdo não tem ele cria um novo

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/ClientBikesRepository.java
> +    List<ClientBikes> listAllClientBikes(Long clientId);
Trocar nome para listAllClientBikeByClientId

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/ClientBikesRepository.java
> +    void editClientBikesById(Long idClientBikes, Integer clientId, Integer bikeId, String plate, LocalDateTime updatedAt);
Mesmo comentário acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/ClientRepository.java
> +    void editClientById(Long idClient, String name, String cpfcnpj, String phone, String nickname, String address, LocalDateTime updatedAt);
Mesmo comentário acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/PartRepository.java
> +    void editPartById(Long idPart, String name, Double value, Integer stockQuantity, Integer bikeId, LocalDateTime updatedAt);
Mesmo comentário acima

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/SupplierRepository.java
> +    Supplier findByName(String name);
Talvez seja mais interessante usar o `s.name LIKE '%:name%` para encontrar por parte do nome tbm

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/SupplierRepository.java
> +    void editSupplierById(Long idSupplier, String name, String phone, String notes, LocalDateTime updatedAt);
Mesmo comentário dos edits

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/BikeService.java
> +        return bikeRepository.listAllBikes();
Não seria Bike?

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/BikeService.java
> +            bikeRepository.editBikeById(editBike.getId(),editBike.getName(),editBike.getBrand(),editBike.getEngineCapacity(),editBike.getYear(),LocalDateTime.now());
Usar o save do JPA

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientBikesService.java
> +public class ClientBikesService {
Mudar o nome para singular

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientBikesService.java
> +            clientBikesRepository.editClientBikesById(editClientBikes.getId(), editClientBikes.getClientId(), editClientBikes.getBikeId(), editClientBikes.getPlate(), LocalDateTime.now());
Usar o Save do JPA

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            clientRepository.editClientById(editClient.getId(),editClient.getName(),editClient.getCpfcnpj(),editClient.getPhone(),editClient.getNickname(),editClient.getAddress(),LocalDateTime.now())
Usar o save do JPA

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/PartService.java
> +            partRepository.editPartById(editPart.getId(), editPart.getName(), editPart.getValue(), editPart.getStockQuantity(), editPart.getBikeId(), LocalDateTime.now());
Usar o save do JPA

2023-09-05 01:06 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/SupplierService.java
> +            supplierRepository.editSupplierById(editSupplier.getId(),editSupplier.getName(),editSupplier.getPhone(),editSupplier.getNotes(),LocalDateTime.now());
Usar o save do JPA

2023-09-05 01:06 UTC, gudominguete commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
era pra ta comentado?

2023-09-05 11:44 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Part.java
> +public class Part {
Peças, vou mexer com as peças usadas para fazer o serviço na moto

2023-09-05 11:53 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/BikeRepository.java
> +    List<Client> listAllBikes();
?

2023-09-05 11:56 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/SupplierRepository.java
> +    Supplier findByName(String name);
Não sei se vai precisar tambem, mas acho bem provavel

2023-09-05 11:57 UTC, LuisRotoly commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
é assim msm

2023-09-06 01:39 UTC, gudominguete requested changes

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/bodyrequestinput/part/EditPartRequest.java
> +
Remover espaço em branco

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Bike.java
> +    private String brand;
Não vale a pena criar uma entidade Brand?

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Client.java
> +    private String cpfcnpj;
cpf/cnpj pode ser uma chave primaria tbm, nao é obrigatório mas mais uma informação mesmo

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/ClientBike.java
> +    private String plate;
A plate não tinha q ta em bike?

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Part.java
> +public class Part {
Não tem um outro nome?

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/ClientBikeRepository.java
> +    @Query(value = "SELECT cb FROM ClientBike cb WHERE cb.plate = :plate")
colocar plate como unico no banco de dados

2023-09-06 01:39 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/repositories/ClientRepository.java
> +    Client findByCpfcnpj(String cpfcnpj);
Colocar cpf/cnpj como unico no banco de dados

2023-09-06 13:51 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Part.java
> +public class Part {
Eu tentei encontrar outro mas não achei nd legal. Eu vi que Part não parece bom

2023-09-06 14:07 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/models/ClientBike.java
> +    private String plate;
Não, Bike vai ser meio que os cadastros de motos existentes. Essa tabela de client bike vai ter a ligação de um cliente, com uma moto e a sua placa entende. Então eu cadastro a moto só uma vez e posso reutilizar ela em quantos clientes forem necessários com placas diferentes

2023-09-06 14:08 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Bike.java
> +    private String brand;
Em um primeiro momento vou deixar assim. Não sei bem ao certo quais os dados que vão entrar aqui.

2023-09-08 00:23 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/models/Part.java
> +public class Part {
Bikepart

2023-09-12 00:43 UTC, gudominguete approved these changes

2023-09-12 11:25 UTC, merged