Adicionando moto a um cliente
LuisRotoly/CRPreparacoesBackEnd pull request #2
Opened 2023-09-15 19:51 UTC by LuisRotoly

2023-09-16 00:44 UTC, gudominguete requested changes

2023-09-16 00:44 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +        Faço a verificação primeiro e altero o método addNewClientBike do ClientBikeService ou deixo do jeito que está(se for do jeito que está eu posso até arrumar os parametros pra não ficar essa l
Faz todas as verificacoes primeiro e depois  faz o resto, nao sei se essa verificacao comentada vai entrar, se nao, acho q ta certo assim

2023-09-16 00:44 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            boolean test = false;
o que esse test faz?

2023-09-16 00:44 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            createClientBikeRequest.setClientId(Math.toIntExact(editClientRequest.getId()));
Que conversão é essa?

2023-09-16 18:46 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            createClientBikeRequest.setClientId(Math.toIntExact(editClientRequest.getId()));
de long pra int

2023-09-18 10:32 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            boolean test = false;
Eu tenho duas listas, uma é a lista de motos que já está no BD e a outra é a lista que está entrando. Caso uma moto que está no BD não apresenta na nova lista eu removo ele do BD, esse teste é o marcador dessa verificação.

2023-09-18 15:27 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            boolean test = false;
Muda o nome da variavel para ter um contexto melhor

2023-09-18 15:28 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            createClientBikeRequest.setClientId(Math.toIntExact(editClientRequest.getId()));
Mas pq? pq nao coloca os dois como long?

2023-09-18 15:52 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            createClientBikeRequest.setClientId(Math.toIntExact(editClientRequest.getId()));
Eu uso o método de findById que usa como padrão int. O que eu posso fazer é no body ao inves de usar Long eu usar Integer, ou então criar meu próprio método findById. Acho que o melhor é receber Integer né?

2023-09-19 23:36 UTC, gudominguete requested changes

2023-09-19 23:36 UTC, gudominguete commented on src/main/java/com/crpreparacoes/crpreparacoes/services/ClientService.java
> +            clientBikeService.addNewClientBike(Math.toIntExact(editClientRequest.getId()),Math.toIntExact(clientBikeDTO.getBike().getId()),clientBikeDTO.getPlate());
Coloca Long como padrão dos IDs, assim nao precisa fazer conversoes

2023-09-22 01:24 UTC, gudominguete approved these changes

2023-09-22 01:27 UTC, merged