Criada venda de peças avulsas
LuisRotoly/CRPreparacoesBackEnd pull request #21
Opened 2023-11-28 12:12 UTC by LuisRotoly

2023-11-30 00:27 UTC, gudominguete requested changes

2023-11-30 00:27 UTC, gudominguete commented on src/main/java/com/crpreparacoes/models/LaborOrBikePartSingleSale.java
> +@Table(name="labor_or_bike_part_single_sale")
Não me parece ser uma entidade isso, qual a intenção dessa tarefa?

2023-11-30 00:27 UTC, gudominguete commented on src/main/java/com/crpreparacoes/models/SingleSale.java
> +    @Column(name="client")
Você não tem uma tabela cliente? Faz referencia com ela aqui

2023-11-30 00:27 UTC, gudominguete commented on src/main/java/com/crpreparacoes/models/SingleSale.java
> +public class SingleSale {
Não ta faltando atributos  nessa classe? Tipo o que foi vendido

2023-11-30 00:27 UTC, gudominguete commented on src/main/java/com/crpreparacoes/services/SingleSaleService.java
> +                    bikePart.setStockQuantity(bikePart.getStockQuantity() - laborOrBikePartSingleSale.getQuantity());
cria uma function para calcular esse valor

2023-11-30 00:27 UTC, gudominguete commented on src/main/java/com/crpreparacoes/services/SingleSaleService.java
> +        List<LaborOrBikePartSingleSale> laborOrBikePartSingleSaleList = laborOrBikePartSingleSaleRepository.getLaborOrBikePartBudgetByBikePartId(bikePartRepository.findById(bikePartId).get().getName(
Separa em linhas, ta bem grande ja

2023-11-30 17:00 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/models/LaborOrBikePartSingleSale.java
> +@Table(name="labor_or_bike_part_single_sale")
São vendas de peças, acessórios, óleo, avulso. O cara chega na mecânica e compra qualquer um desses itens sem precisar fazer nenhum serviço. Tenho duas entidades, uma chama "venda avulsa" e a outra é essa que vc tá vendo.
A venda avulsa por enquanto tem o nome do cliente e a data. Essa classe aqui vai ter as peças, quantidades e os valores de cada um. Então teria que existir duas classes diferentes

2023-11-30 17:06 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/models/SingleSale.java
> +    @Column(name="client")
Tem mas as meninas não querem ter que criar um cliente e cadastrar. Tem que ser algo mais facil e simples, entao só o nome já é o suficiente

2023-11-30 17:08 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/models/SingleSale.java
> +public class SingleSale {
Eu falei ali em cima. O que ainda falta é a parte do financeiro que eu ainda não fiz. O que foi vendido está na tabela LaborOrBikePartSingleSale

2023-12-01 00:33 UTC, gudominguete commented on src/main/java/com/crpreparacoes/models/SingleSale.java
> +    @Column(name="client")
Isso pode ser ruim no futuro

2023-12-04 00:18 UTC, gudominguete approved these changes

2023-12-05 11:46 UTC, merged