Alterações feitas no orçamento
LuisRotoly/CRPreparacoesBackEnd pull request #7
Opened 2023-10-03 21:06 UTC by LuisRotoly

2023-10-03 23:53 UTC, gudominguete requested changes

2023-10-03 23:53 UTC, gudominguete commented on src/main/java/com/crpreparacoes/bodyrequestinput/budget/CreateBudgetRequest.java
> +    private Integer kilometers;
quilometros nao eh um bom nome por ser unidade de medida, eh bom mostrar o q ela representa, tipo DistanciaPercorrida, DistanciaRodada, etc..

2023-10-03 23:53 UTC, gudominguete commented on src/main/java/com/crpreparacoes/bodyrequestinput/budget/EditBudgetRequest.java
> +    private String payment;
O que seria esse payment? Forma de pagamento?

2023-10-03 23:53 UTC, gudominguete commented on src/main/java/com/crpreparacoes/dto/BikeDTO.java
> +    private String bikeBrandName;
Aqui não precisa repetir o bike, visto que já é DTO de bike

2023-10-03 23:53 UTC, gudominguete commented on src/main/java/com/crpreparacoes/dto/BikeDTO.java
> +    private String bikeName;
O que seria nome da bike?

2023-10-03 23:53 UTC, gudominguete commented on src/main/java/com/crpreparacoes/repositories/ClientBikeRepository.java
> +import com.crpreparacoes.models.Bike;
Ta sendo usado esse import?

2023-10-04 00:05 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/dto/BikeDTO.java
> +    private String bikeName;
O nome dela mesmo

2023-10-04 00:05 UTC, LuisRotoly commented on src/main/java/com/crpreparacoes/bodyrequestinput/budget/EditBudgetRequest.java
> +    private String payment;
sim

2023-10-05 01:36 UTC, gudominguete requested changes

2023-10-05 01:36 UTC, gudominguete commented on src/main/java/com/crpreparacoes/bodyrequestinput/budget/EditBudgetRequest.java
> +    private String paymentFormat;
Colocar enum

2023-10-05 01:36 UTC, gudominguete commented on src/main/java/com/crpreparacoes/bodyrequestinput/budget/CreateBudgetRequest.java
> +    private String paymentFormat;
Colocar enum

2023-10-05 01:36 UTC, gudominguete commented on src/main/java/com/crpreparacoes/dto/BudgetDTO.java
> +    private String paymentFormat;
Enum

2023-10-06 00:13 UTC, gudominguete approved these changes

2023-10-06 20:47 UTC, merged